version: "3.7"

services:
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Password123",
          "-Q",
          "SELECT 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
